export enum ROUTES {
  SELECT_METHOD = "rozoPaySelectMethod",
  SELECT_TOKEN = "rozoPaySelectToken",
  SELECT_AMOUNT = "rozoPaySelectAmount",
  SELECT_EXTERNAL_AMOUNT = "rozoPaySelectExternalAmount",
  SELECT_EXCHANGE = "rozoPaySelectExchange",
  SELECT_DEPOSIT_ADDRESS_AMOUNT = "rozoPaySelectDepositAddressAmount",
  SELECT_WALLET_AMOUNT = "rozoPaySelectWalletAmount",
  SELECT_ZKP2P = "rozoPaySelectZKP2P",
  WAITING_EXTERNAL = "rozoPayWaitingExternal",
  WAITING_WALLET = "rozoPayWaitingWallet",
  SELECT_DEPOSIT_ADDRESS_CHAIN = "rozoPaySelectDepositAddressChain",
  WAITING_DEPOSIT_ADDRESS = "rozoPayWaitingDepositAddress",
  PAY_WITH_TOKEN = "rozoPayPayWithToken",
  CONFIRMATION = "rozoPayConfirmation",
  SOLANA_CONNECT = "rozoPaySolanaConnect",
  SOLANA_CONNECTOR = "rozoPaySolanaConnector",
  SOLANA_SELECT_AMOUNT = "rozoPaySolanaSelectAmount",
  SOLANA_PAY_WITH_TOKEN = "rozoPaySolanaPayWithToken",
  ERROR = "rozoPayError",

  // Unused routes. Kept to minimize connectkit merge conflicts.
  ONBOARDING = "onboarding",
  ABOUT = "about",
  CONNECTORS = "connectors",
  MOBILECONNECTORS = "mobileConnectors",
  CONNECT = "connect",
  DOWNLOAD = "download",
  SWITCHNETWORKS = "switchNetworks",
}
